#!/usr/bin/env zsh
# -*- mode: sh; sh-shell: zsh; sh-indentation: 4; sh-basic-offset: 4; coding: utf-8; -*-
# vim: ft=zsh:sw=4:ts=4:et
#
# Time-stamp: "Last Modified 2023-03-10 05:35:13 by Gene De Lisa, genedelisa"
#
# File: onetest
# Description: Run just the specified test
#
# Gene De Lisa
# gene@rockhoppertech.com
# http://rockhoppertech.com/blog/
# License - http://unlicense.org
################################################################################
# https://google.github.io/styleguide/shellguide.html#s7-naming-conventions
################################################################################
#
#                   _            _
#   ___  _ __   ___| |_ ___  ___| |_
#  / _ \| '_ \ / _ \ __/ _ \/ __| __|
# | (_) | | | |  __/ ||  __/\__ \ |_
#  \___/|_| |_|\___|\__\___||___/\__|
#
#
################################################################################

# -R reset zsh options
# -L options LOCAL_OPTIONS, LOCAL_PATTERNS and LOCAL_TRAPS will be set
emulate -LR zsh

################################################################################

local SCRIPT_NAME=${ZSH_SCRIPT:t:r}

usage() {
    readonly local help_text="""
Run just the specified test.

Usage: ${SCRIPT_NAME} testname

To list the tests:
xcrun swift test -l
xcrun swift test --list-tests

"""
    print ${help_text}
    exit 0
}

main() {
    testname=$1
    print -- "Running test $testname"
    xcrun swift test --filter $testname
    return ${status}
}

###############################################################################
# The main flow
###############################################################################

[[ $# -lt 1 ]] && usage

main "${@}"
return ${status}
